language: r
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtcl8.5 libtcl8.5-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'