language: r
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtcl8.4 libtcl8.4-dbg

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'